config/routes.rb
Prngs::Application.routes.draw do

  root :to => "home#index"
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/login", to: "sessions#new", :as => "login"
  match "/logout", to: "sessions#destroy", :as => "logout"

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"

  post "/deauth/:provider", to: "users#deauth", :as => "deauth"

  resources :users

  resources :sources

  resources :mentions

  resources :artists

  resources :videos do
    get :autocomplete_video_and_sources_and_artists_search, :on => :collection
  end

  post "/search", to: "searches#search", :as => "search"
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_and_belongs_to_many :videos

  validates_presence_of :name
  validates_uniqueness_of :name

  serialize :images
  serialize :biographies

  include NamedScopes::DateTime
  include NamedScopes::Popularity

  searchable do
    text    :name
    integer :popularity do
      popularity.to_f
    end
    integer :videos do
      videos.count
    end
    time    :created_at
  end


  def bio
    biographies.length > 0 ? biographies.sort_by{ |bio| bio["text"].length }.last["text"] : ""
  end

  def image
    images.length > 0 ? images.first["#text"] : ""
  end

  def self.primary_search(query)
    Artist.solr_search do
      fulltext query
      order_by :created_at, :desc
      order_by :popularity, :desc
      order_by :videos, :desc
      paginate :per_page => 10
    end
  end

  def self.construct(artist)
    Artist.find_or_create_by_name(
      :name => artist.name,
      :echonest_id => artist.id
    )
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @videos = @artist.videos.page(params[:page]).per(10)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_artist.html.haml
%h1= artist.name

app/views/artists/_thumb.html.haml
%li.artist.thumb.entity
  .image.largesquare
    = link_to artist_path(artist), :class => "thumbnail square" do
      = image_tag(artist.image, :alt => artist.name)
  .meta
    %h3= link_to artist.name, artist_path(artist)
    .bio= truncate(artist.bio, :length => 217)
  .loading

app/views/artists/_videos.html.haml
%ul.media-list.artist
  = render :collection => @videos, :as => :video, :partial => "videos/thumb"

  = paginate @videos, :id => "pagination"

app/views/artists/index.html.haml
= content_for_or_pjax :heading do
  %h1 Artists

app/views/artists/show.html.haml
= content_for_or_pjax :heading do
  %h1= @artist.name
  .artist-image= image_tag @artist.image, :alt => @artist.name

= render "mentions/mentions"

= render "artists/videos"