config/routes.rb
Prngs::Application.routes.draw do

  root :to => "home#index"
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/login", to: "sessions#new", :as => "login"
  match "/logout", to: "sessions#destroy", :as => "logout"

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"

  post "/deauth/:provider", to: "users#deauth", :as => "deauth"

  resources :users

  resources :sources

  resources :mentions

  resources :artists

  resources :videos do
    get :autocomplete_video_and_sources_and_artists_search, :on => :collection
  end

  post "/search", to: "searches#search", :as => "search"
end

app/views/shared/_facebook_js_sdk.html.haml
#fb-root

:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : "#{FB_APP_ID}",
      channelUrl : "#{CHANNEL_URL}",
      status     : true,
      cookie     : true,
      xfbml      : true
    });
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     d.getElementsByTagName('head')[0].appendChild(js);
   }(document));

app/views/shared/_loaders.html.haml
= render "shared/loaders/cheerloader"
= render "shared/loaders/levitator"

app/views/shared/_open_graph.html.haml
= og_title(@og.try(:title) || APP_NAME)
= og_type(@og.try(:type) || "website")
= og_url(@og.try(:url) || APP_URL)
= og_image(@og.try(:image) || APP_IMAGE)
= og_site_name(APP_NAME)
= og_description(@og.try(:description) || APP_DESCRIPTION)
= og_fb_app_id(FB_APP_ID)

app/views/shared/_search.html.haml
#primary_search.search-form
  = form_tag search_path do
    .clearfix.primary-search
      = text_field_tag :video_or_sources_or_artists_name, nil, :autocomplete => autocomplete_video_and_sources_and_artists_search_videos_path, :class => "xlarge span6 search-query", :spellcheck => "false", :placeholder => "Enter an Artist, Blog, or Video..."
      .loading
      = submit_tag "Search", :class => "btn primary"

app/views/shared/_session.html.haml
- if current_user
  .session.module.logged-in
    .avatar= user_avatar(current_user)
    .current-user= link_to current_user.name, user_path(current_user)
    .authentications
      .twitter= connection_status("twitter", current_user)
      .facebook= connection_status("facebook", current_user)
    = link_to "Log Out", logout_path, :class => "logout", :'data-skip-pjax' => true
- else
  .session.module.logged-out
    = link_to "Log In with Twitter", "/auth/twitter", :class => "button twitter login", :'data-skip-pjax' => true
    = link_to "Log In with Facebook", "/auth/facebook", :class => "button facebook login", :'data-skip-pjax' => true

app/views/shared/_session_button.html.haml
.btn-group.session
  = link_to truncate(current_user.name, :length => 28, :omission => ''), user_path(current_user), :class => "btn current-user" if current_user
  = link_to "Connect an Account", "#", :class => "btn" unless current_user
  %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    %span.caret
  %ul.dropdown-menu.session
    - if current_user
      .avatar= user_avatar(current_user)
      .authentications
        %strong Connections
        .twitter= connection_status("twitter", current_user)
        .facebook= connection_status("facebook", current_user)
      %li.divider
      %li.action= link_to "My Profile", user_path(current_user)
      %li.action= link_to "Account Settings", "#"
      %li.action= link_to "Help Center", "#"
      %li.divider
      %li.action.logout= link_to "Log Out", logout_path, :'data-skip-pjax' => true
    - else
      %li.action.login= link_to "Log In with Twitter", "/auth/twitter", :class => "button twitter login", :'data-skip-pjax' => true
      %li.action.login= link_to "Log In with Facebook", "/auth/facebook", :class => "button facebook login", :'data-skip-pjax' => true